cleansys/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from cleansys.settings import BASE_URL, APPLY_BASE_URL_TO_URL_PATTERNS

if APPLY_BASE_URL_TO_URL_PATTERNS:
    urlpatterns = [
        url(r'^{}'.format(BASE_URL[1:]), include('webinterface.urls')),

    ]
else:
    urlpatterns = [
        url(r'^', include('webinterface.urls')),
    ]
# urlpatterns += url(r'^admin/', admin.site.urls)

putzplan_generator/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('webinterface.urls')),
]

webinterface/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from webinterface.views import *
from webinterface.api_views import *
from webinterface.form_views import *
from webinterface.decorators import *
from django.conf.urls import include
from rest_framework import routers

from django.views.generic.base import RedirectView

router = routers.DefaultRouter()  # https://www.django-rest-framework.org/api-guide/routers/#defaultrouter
router.register(r'schedules', ScheduleViewSet)
router.register(r'schedulegroups', ScheduleGroupViewSet)
router.register(r'cleaners', CleanerViewSet)
router.register(r'affiliations', AffiliationViewSet)
router.register(r'cleaningweeks', CleaningWeekViewSet)
router.register(r'assignments', AssignmentViewSet)
router.register(r'tasktemplates', TaskTemplateViewSet)
router.register(r'task', TaskViewSet)
router.register(r'dutyswitches', DutySwitchViewSet)

app_name = 'webinterface'
urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy("webinterface:cleaner-no-page")), name='welcome'),
    path('login/', LoginView.as_view(template_name="webinterface/generic_form.html",
                                     extra_context={'title': "Login", 'add_home_button': True},
                                     authentication_form=AuthFormWithSubmit), name='login'),
    path('login-per-klick/', LoginByClickView.as_view(), name='login-by-click'),
    path('logout/', login_required(LogoutView.as_view()), name='logout'),
    path('admin/', must_be_admin(AdminView.as_view()), name='admin'),
    path('documentation/', DocumentationView.as_view(), name='docs'),
    path('admin/faq', must_be_admin(AdminFAQView.as_view()), name='admin-faq'),
    path('admin/daten', must_be_admin(AdminUpdateView.as_view()), name='admin-edit'),

    path('affiliation-edit/<int:pk>/', must_be_admin(AffiliationUpdateView.as_view()), name='affiliation-edit'),
    path('affiliation-delete/<int:pk>/', must_be_admin(AffiliationDeleteView.as_view()),
         name='affiliation-delete'),
    path('putzer/<int:pk>/zugehoerigkeiten/', login_required(AffiliationNewView.as_view()),
         name='affiliation-list'),
    path('putzer/<int:pk>/zugehoerigkeiten/p<int:cleaner_page>/', login_required(AffiliationNewView.as_view()),
         name='affiliation-list-with-cleaner-page'),

    path('putzen/<int:cleaning_week_pk>/', login_required(AssignmentTasksView.as_view()),
         name='assignment-tasks'),
    path('putzen/<int:cleaning_week_pk>/s<int:schedule_page>/', login_required(AssignmentTasksView.as_view()),
         name='assignment-tasks-back-to-schedule'),
    path('putzen/<int:cleaning_week_pk>/p<int:cleaner_page>/', login_required(AssignmentTasksView.as_view()),
         name='assignment-tasks-back-to-cleaner'),
    path('assignment-create/<int:schedule_pk>/<int:page>/', must_be_admin(AssignmentCreateView.as_view()),
         name='assignment-create-back-to-schedule'),
    path('assignment-create/<int:schedule_pk>/<int:page>/<int:initial_begin>/<int:initial_end>/',
         must_be_admin(AssignmentCreateView.as_view()),
         name='assignment-create-init'),
    path('assignment-edit/<int:pk>/<int:page>/', must_be_admin(AssignmentUpdateView.as_view()),
         name='assignment-edit'),

    path('du/seite<int:page>/', login_required(CleanerView.as_view()), name='cleaner'),
    path('du/', login_required(CleanerView.as_view()), name='cleaner-no-page'),
    path('du/dienst<int:assignment_pk>/', login_required(CleanerView.as_view()), name='cleaner-no-page-to-assignment'),
    path('du/kalender/', login_required(CleanerCalendarView.as_view()), name='cleaner-calendar'),
    path('putzer-analytics/', login_required(CleanerAnalyticsView.as_view()), name='cleaner-analytics'),
    path('putzer-analytics/p<int:cleaner_page>/', login_required(CleanerAnalyticsView.as_view()),
         name='cleaner-analytics-with-cleaner-page'),

    path('putzer/neu/', must_be_admin(CleanerNewView.as_view()), name='cleaner-new'),
    path('putzer/<int:pk>/', login_required(CleanerUpdateView.as_view()),
         name='cleaner-edit'),
    path('putzer/<int:pk>/p<int:cleaner_page>', login_required(CleanerUpdateView.as_view()),
         name='cleaner-edit-with-cleaner-page'),
    path('cleaner-delete/<int:pk>/', must_be_admin(CleanerDeleteView.as_view()), name='cleaner-delete'),

    path('cleaning-week-tasks/<int:pk>/<int:page>/', must_be_admin(TaskCreateView.as_view()),
         name='cleaning-week-tasks'),
    path('cleaning-week-edit/<int:pk>/<int:page>/', must_be_admin(CleaningWeekUpdateView.as_view()),
         name='cleaning-week-edit'),
    path('cleaning-week-delete/<int:pk>/<int:page>/', must_be_admin(CleaningWeekDeleteView.as_view()),
         name='cleaning-week-delete'),

    path('tauschen/<int:assignment_pk>/<int:page>', login_required(DutySwitchNewView.as_view()),
         name='dutyswitch-create'),
    path('tausch-bearbeiten/<int:dutyswitch_pk>/<int:page>', login_required(DutySwitchUpdateView.as_view()),
         name='dutyswitch-update'),
    path('tauschanfrage-akzeptieren/<int:pk>/<int:page>', login_required(DutySwitchAcceptView.as_view()),
         name='dutyswitch-accept'),
    path('tauschanfrage-akzeptieren/<int:pk>', login_required(DutySwitchAcceptView.as_view()),
         name='dutyswitch-accept-no-cleaner-page'),
    path('tauschanfrage-loeschen/<int:pk>/<int:page>', login_required(DutySwitchDeleteView.as_view()),
         name='dutyswitch-delete'),
    path('tauschvorschlag-ablehnen/<int:pk>', login_required(DutySwitchRejectProposalView.as_view()),
         name='dutyswitch-reject-proposal'),

    path('putzplan-liste/', login_required(ScheduleList.as_view()), name='schedule-list'),
    path('putzplan/<slug:slug>/ab<int:week>/druckansicht/', login_required(SchedulePrintView.as_view()),
         name='schedule-print-view'),
    # path('putzplan/<slug:slug>/seite<int:page>/<slug:highlight_slug>/', login_required(ScheduleView.as_view()),
    #      name='schedule-highlight'),
    path('putzplan/<slug:slug>/seite<int:page>/', login_required(ScheduleView.as_view()), name='schedule'),
    path('putzplan/<slug:slug>/analytics/', login_required(ScheduleAnalyticsView.as_view()),
         name='schedule-analytics-view'),
    path('putzplan/<slug:slug>/analytics/s<int:schedule_page>/', login_required(ScheduleAnalyticsView.as_view()),
         name='schedule-analytics-view-with-schedule-page'),
    path('putzplan/<slug:slug>/', login_required(ScheduleView.as_view()), name='schedule-no-page'),

    path('schedule-new/', must_be_admin(ScheduleNewView.as_view()), name='schedule-new'),
    path('schedule-edit/<int:pk>/', must_be_admin(ScheduleUpdateView.as_view()),
         name='schedule-edit'),
    path('schedule-delete/<int:pk>/', must_be_admin(ScheduleDeleteView.as_view()),
         name='schedule-delete'),
    path('schedule/<int:pk>/tasks/', must_be_admin(ScheduleTaskList.as_view()),
         name='schedule-task-list'),
    path('schedule/<int:pk>/tasks/new/', must_be_admin(TaskTemplateNewView.as_view()),
         name='schedule-task-new'),
    path('schedule-overview', must_be_admin(ScheduleOverView.as_view()),
         name='schedule-overview'),

    path('schedule-group-new/', must_be_admin(ScheduleGroupNewView.as_view()),
         name='schedule-group-new'),
    path('schedule-group-edit/<int:pk>/', must_be_admin(ScheduleGroupUpdateView.as_view()),
         name='schedule-group-edit'),
    path('schedule-group-delete/<int:pk>/', must_be_admin(ScheduleGroupDeleteView.as_view()),
         name='schedule-group-delete'),

    path('geputzt/<int:assignment_pk>/<int:task_pk>', login_required(TaskCleanedView.as_view()),
         name='task-cleaned'),
    path('task-edit/<int:pk>/', must_be_admin(TaskTemplateUpdateView.as_view()), name='task-edit'),
    path('task-delete/<int:pk>/', must_be_admin(TaskTemplateDeleteView.as_view()), name='task-delete'),

    path('api/', include((router.urls, 'webinterface'), namespace="api"))
]

webinterface/templates/webinterface/admin_dashboard.html
{% extends "webinterface/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Einstellungen
{% endblock %}

{% block bootstrap_meta_tags %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content='width=device-width, initial-scale=1, maximum-scale=1' name='viewport' />
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            {% if action_needed_cleaners %}
                <div class="alert alert-warning" role="alert" style="margin: 5px 0">
                    Bei Putzern sind Handlungen notwendig!</div>
            {% endif %}
            {% if action_needed_schedules %}
                <div class="alert alert-warning" role="alert" style="margin: 5px 0">
                    Bei Putzplänen sind Handlungen notwendig!</div>
            {% endif %}
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-6">
                <h2>Admin Daten
                    <a class="btn btn-default %}"
                       href="{% url 'webinterface:admin-edit' %}" role="button">
                        <span class="glyphicon glyphicon-cog"></span> Bearbeiten
                    </a>
                </h2>
                <div class="well">
                    Admin Email: <strong>{{ request.user.email }}</strong>
                </div>
                <h2>Putzer
                    <a class="btn btn-default %}"
                       href="{% url 'webinterface:cleaner-new' %}" role="button">
                        <span class="glyphicon glyphicon-plus"></span> Neuer Putzer
                    </a>
                    <a href="{% url 'webinterface:cleaner-analytics' %}"
                       class="btn btn-default" role="button">
                        <span class="glyphicon glyphicon-stats"></span> Analytics
                    </a>
                    <a href="{% url 'webinterface:admin-faq' %}"
                       class="btn btn-info" role="button">
                        <span class="glyphicon glyphicon-info-sign"></span> FAQ
                    </a>
                </h2>
                <div class="well">
                    {% if action_needed_cleaners %}
                        <div class="row">
                            <h4>Putzer mit Meldungen</h4>
                            {% for cleaner in action_needed_cleaners %}
                                {% include "webinterface_snippets/cleaner_panel.html" %}
                            {% endfor %}
                        </div>
                    {% endif %}
                    {% if active_cleaner_list %}
                        <div class="row">
                            <h4>Putzer, die zur Zeit eine aktive Zugehörigkeit haben <span class="badge">{{ active_cleaner_list.count }}</span></h4>
                            {% for cleaner in active_cleaner_list %}
                                {% include "webinterface_snippets/cleaner_panel.html" %}
                            {% empty %}
                                Keine aktiven Putzer
                            {% endfor %}
                        </div>
                    {% endif %}
                    {% if inactive_cleaner_list %}
                        <div class="row">
                            <h4>
                                Putzer, die nicht mehr aktiv sind
                                <span class="badge">{{ inactive_cleaner_list.count }}</span>
                            </h4>
                            {% for cleaner in inactive_cleaner_list %}
                                {% include "webinterface_snippets/cleaner_panel.html" %}
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-xs-12 col-sm-6">
                <h2>Putzpläne
                    <a class="btn btn-default" href="{% url 'webinterface:schedule-new' %}" role="button">
                        <span class="glyphicon glyphicon-plus"></span> Neuer Putzplan</a>
                    <a class="btn btn-info" href="{% url 'webinterface:schedule-overview' %}" role="button">
                        <span class="glyphicon glyphicon-search"></span> Übersicht</a>
                </h2>
                <div class="well">
                    {% if action_needed_schedules %}
                        <div class="row">
                            <h4>Putzpläne mit Meldungen</h4>
                            {% for schedule in action_needed_schedules %}
                                {% include 'webinterface_snippets/schedule_panel.html' %}
                            {% endfor %}
                        </div>
                    {% endif %}
                    {% if active_schedule_list %}
                        <div class="row">
                            <h4>Aktive Putzpläne</h4>
                            {% for schedule in active_schedule_list %}
                                {% include 'webinterface_snippets/schedule_panel.html' %}
                            {% endfor %}
                        </div>
                    {% endif %}
                    {% if disabled_schedule_list %}
                        <div class="row">
                            <h4>Deaktivierte Putzpläne</h4>
                            {% for schedule in disabled_schedule_list %}
                                {% include 'webinterface_snippets/schedule_panel.html' %}
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <h2>Putzplan-Gruppierungen
                    <a class="btn btn-default" href="{% url 'webinterface:schedule-group-new' %}"
                       role="button">
                    <span class="glyphicon glyphicon-plus"></span> Neue Putzplan-Gruppierung</a></h2>
                <div class="well">
                    <div class="row">
                        {% for group in schedule_group_list %}
                            <div class="col-xs-12 col-sm-6" style="padding: 5px">
                                <a class="btn btn-primary btn-block" role="button" style="white-space: normal"
                                   href="{% url 'webinterface:schedule-group-edit' group.pk %}">
                                    <span class="glyphicon glyphicon-cog"></span> {{ group.name }}
                                </a>
                            </div>
                        {% empty %}
                            <p>Es gibt keine...</p>
                        {% endfor %}
                    </div>
                </div>

                <a class="btn btn-default btn-block" role="button" href="{% url 'webinterface:logout' %}">Logout</a>
                <br><br><br>
            </div>
        </div>
    </div>
{% endblock %}

webinterface/templates/webinterface/cleaner.html
{% extends "webinterface/mobile_first_body.html" %}
{% load crispy_forms_tags %}
{% load tz %}

{% block title %}
    Deine Putzdienste
{% endblock %}

{% block main %}
    <div class="row">
        <div class="btn btn-group btn-group-md btn-group-justified" role="group">
            {% include "webinterface_snippets/button_to_schedule_list_page.html" %}
        </div>
    </div>
    <h2>Hallo {{ cleaner.name }}!</h2>
    {% with curr_affil=cleaner.current_affiliation %}
        <p>
            Du bist der Putzplan-Gruppe <b>{{ curr_affil.group }}</b> bis zum
            <b>{{ curr_affil.end_as_date|date:"d. b. Y" }}</b> zugewiesen.
            <a href="{% url 'webinterface:affiliation-list-with-cleaner-page' cleaner.pk page_obj.number %}">
                Mehr zu deinen Zugehörigkeiten.
            </a>
        </p>
    {% endwith %}

    <div class="row">
        <div class="panel panel-primary" style="margin: 0">
            <div class="panel-heading">
                <h4>Deine nächsten Putzdienste</h4>
            </div>
        </div>
    </div>
    <div class="row" style="padding: 5px">
        <div class="col-xs-12">
            <a class="btn btn-default btn-block" role="button" href="{% url 'webinterface:cleaner-calendar' %}">
                <span class="glyphicon glyphicon-calendar"></span> Dein Putzkalender
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            {% include "webinterface_snippets/cleaner_pagination_buttons.html" %}
        </div>
    </div>
    {% for assignment in assignment_list %}
        <div class="row" style="background-color: {% cycle "#FFFFFF" "#EEEEEE" %};">
            <div class="col-xs-12">
                <div class="row" style="padding: 0.25em">
                    <div class="col-xs-12">
                        Putzplan <span class="glyphicon glyphicon-play"></span> <b>{{ assignment.schedule.name }}</b>
                    </div>

                    <div class="col-xs-6">
                        <span class="glyphicon glyphicon-calendar"></span> {{ assignment.assignment_date|date:"d. M y" }}
                    </div>

                    <div class="col-xs-6">
                        {% if assignment.other_cleaners_in_week_for_schedule.exists %}
                            <span class="glyphicon glyphicon-user"></span> Mit
                            {% for cleaner in assignment.other_cleaners_in_week_for_schedule.all %}
                                {{ cleaner.name }}{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-6">
                        {% if not assignment.has_passed and not assignment.cleaning_week.all_tasks_are_completed %}
                            {% if assignment.switch_requested %}
                                <a class="btn btn-warning btn-sm"
                                   href="{% url 'webinterface:dutyswitch-update' assignment.switch_requested.pk page_obj.number %}"
                                   role="button" style="white-space: normal; margin: 0.5em">
                                    <span class="glyphicon glyphicon-cog"></span> Tauschanfrage
                                </a>
                            {% else %}
                                <a class="btn btn-default btn-sm"
                                   href="{% url 'webinterface:dutyswitch-create' assignment.pk page_obj.number %}"
                                   role="button" style="white-space: normal; margin: 0.5em">
                                    Tauschen <span class="glyphicon glyphicon-random"></span>
                                </a>
                            {% endif %}
                        {% endif %}
                    </div>
                    <div class="col-xs-6">
                        <a role="button" style="white-space: nowrap; margin: 0.5em"
                           class="btn {% if assignment.tasks_are_ready_to_be_done %}btn-success{% else %}btn-default{% endif %} btn-sm"
                           href="{% url 'webinterface:assignment-tasks-back-to-cleaner' assignment.cleaning_week.pk page_obj.number %}">
                            {% if assignment.tasks_are_ready_to_be_done %}
                                Los <span class="glyphicon glyphicon-play-circle"></span>
                            {% else %}
                                <span class="glyphicon glyphicon-list"></span> Aufgaben
                            {% endif %}
                            {% if not assignment.cleaning_week.is_in_future %}
                                <span class="label label-default">
                                                {{ assignment.cleaning_week.completed_tasks.count }} /
                                                {{ assignment.cleaning_week.task_set.count }}
                                            </span>
                            {% endif %}
                        </a>
                    </div>
                </div>
            </div>
        </div>
    {% empty %}
        Keine Putzdienste zu zeigen
    {% endfor %}
    <div class="row">
        <div class="col-xs-12">
            {% include "webinterface_snippets/cleaner_pagination_buttons.html" %}
        </div>
    </div>
    <br>

    {% comment %}
    <div class="row" style="padding: 5px">
        <div class="col-xs-12">
            <a class="btn btn-default btn-block"
               href="{% url 'webinterface:affiliation-list-with-cleaner-page' cleaner.pk page_obj.number %}"
               role="button">
                <span class="glyphicon glyphicon-th-list"></span> Deine Zugehörigkeiten
            </a>
        </div>
    </div>
    {% endcomment %}

    <div class="row" style="padding: 5px">
        <div class="col-xs-12">
            <a class="btn btn-default btn-block"
               href="{% url 'webinterface:cleaner-edit-with-cleaner-page' cleaner.pk page_obj.number %}"
               role="button">
                <span class="glyphicon glyphicon-envelope"></span> Email-Einstellungen
            </a>
        </div>
    </div>

    <div class="row" style="padding: 5px">
        <div class="col-xs-12">
            <a href="{% url 'webinterface:cleaner-analytics-with-cleaner-page' page_obj.number %}"
               class="btn btn-default btn-block" role="button">
                <span class="glyphicon glyphicon-stats"></span> Analytics zu allen Putzern
            </a>
        </div>
    </div>

    <div class="row" style="padding: 5px">
        <div class="col-xs-12">
            <a class="btn btn-default btn-block" role="button" href="{% url 'webinterface:logout' %}">
                Du bist nicht {{ cleaner.name }}? <span class="glyphicon glyphicon-arrow-right"></span> Logout
            </a>
        </div>
    </div>
{% endblock %}

webinterface/templates/webinterface/config.html
{% extends "webinterface/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Einstellungen
{% endblock %}

{% block bootstrap_meta_tags %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content='width=device-width, initial-scale=1, maximum-scale=1' name='viewport' />
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            {% if action_needed_cleaners %}
                <div class="alert alert-warning" role="alert" style="margin: 5px 0">
                    Bei Putzern sind Handlungen notwendig!</div>
            {% endif %}
            {% if action_needed_schedules %}
                <div class="alert alert-warning" role="alert" style="margin: 5px 0">
                    Bei Putzplänen sind Handlungen notwendig!</div>
            {% endif %}
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-6">
                <h2>Putzer
                    <a class="btn btn-default {% if not active_schedule_group_list %}disabled{% endif %} %}"
                       href="{% url 'webinterface:cleaner-new' %}" role="button">
                        <span class="glyphicon glyphicon-plus"></span> Neuer Putzer
                    </a>
                    <a href="{% url 'webinterface:cleaner-analytics' %}"
                       class="btn btn-default" role="button">
                        <span class="glyphicon glyphicon-dashboard"></span> Analytics
                    </a>
                </h2>
                <div class="well">
                    {% if action_needed_cleaners %}
                        <div class="row">
                            <h4>Putzer mit Meldungen</h4>
                            {% for cleaner in action_needed_cleaners %}
                                {% include "webinterface_snippets/cleaner_panel.html" %}
                            {% endfor %}
                        </div>
                    {% endif %}
                    {% if active_cleaner_list %}
                        <div class="row">
                            <h4>Putzer, die zur Zeit eine aktive Zugehörigkeit haben <span class="badge">{{ active_cleaner_list.count }}</span></h4>
                            {% for cleaner in active_cleaner_list %}
                                {% include "webinterface_snippets/cleaner_panel.html" %}
                            {% empty %}
                                Keine aktiven Putzer
                            {% endfor %}
                        </div>
                    {% endif %}
                    {% if inactive_cleaner_list %}
                        <div class="row">
                            <h4>
                                Putzer, die nicht mehr aktiv sind
                                <span class="badge">{{ inactive_cleaner_list.count }}</span>
                            </h4>
                            {% for cleaner in inactive_cleaner_list %}
                                {% include "webinterface_snippets/cleaner_panel.html" %}
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-xs-12 col-sm-6">
                <h2>Putzpläne
                    <a class="btn btn-default" href="{% url 'webinterface:schedule-new' %}" role="button">
                    <span class="glyphicon glyphicon-plus"></span> Neuer Putzplan</a></h2>
                <div class="well">
                    {% if action_needed_schedules %}
                        <div class="row">
                            <h4>Putzpläne mit Meldungen</h4>
                            {% for schedule in action_needed_schedules %}
                                {% include 'webinterface_snippets/schedule_panel.html' %}
                            {% endfor %}
                        </div>
                    {% endif %}
                    {% if active_schedule_list %}
                        <div class="row">
                            <h4>Aktive Putzpläne</h4>
                            {% for schedule in active_schedule_list %}
                                {% include 'webinterface_snippets/schedule_panel.html' %}
                            {% endfor %}
                        </div>
                    {% endif %}
                    {% if disabled_schedule_list %}
                        <div class="row">
                            <h4>Deaktivierte Putzpläne</h4>
                            {% for schedule in disabled_schedule_list %}
                                {% include 'webinterface_snippets/schedule_panel.html' %}
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <h2>Putzplan-Gruppierungen
                    <a class="btn btn-default" href="{% url 'webinterface:schedule-group-new' %}"
                       role="button">
                    <span class="glyphicon glyphicon-plus"></span> Neue Putzplan-Gruppierung</a></h2>
                <div class="well">
                    <div class="row">
                        {% for group in active_schedule_group_list %}
                            <div class="col-xs-12 col-sm-6" style="padding: 5px">
                                <a class="btn btn-primary btn-block" role="button" style="white-space: normal"
                                   href="{% url 'webinterface:schedule-group-edit' group.pk %}">
                                    <span class="glyphicon glyphicon-cog"></span> {{ group.name }}
                                </a>
                            </div>
                        {% empty %}
                            <p>Keine Putzplan-Gruppen zu Zeigen...</p>
                        {% endfor %}
                        {% if disabled_schedule_group_list %}
                            <div class="col-xs-12"><h3>Deaktivierte Putzplan-Gruppen</h3></div>
                            {% for group in disabled_schedule_group_list %}
                            <div class="col-xs-12 col-sm-6" style="padding: 5px">
                                <a class="btn btn-default btn-block" role="button" style="white-space: normal"
                                   href="{% url 'webinterface:schedule-group-edit' group.pk %}">
                                    <span class="glyphicon glyphicon-cog"></span> {{ group.name }}
                                </a>
                            </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>

                <a class="btn btn-default btn-block" role="button" href="{% url 'webinterface:logout' %}">Logout</a>
                <br><br><br>
            </div>
        </div>
    </div>
{% endblock %}

webinterface/templates/webinterface/schedule_task_list.html
{% extends "webinterface/mobile_first_body.html" %}
{% load crispy_forms_tags %}
{% load tz %}

{% block title %}
Aufgaben für {{ schedule }}
{% endblock %}

{% block main %}
    <div class="row">
        <div class="btn btn-group btn-group-md btn-group-justified" role="group">
            {% include 'webinterface_snippets/home_button.html' %}
        </div>
    </div>
    <h2>Aufgaben für <b>{{ schedule }}</b></h2>

    <div class="row">
        <div class="btn btn-group btn-group-md btn-group-justified" role="group">
            <a class="btn btn-default" role="button" href="{% url 'webinterface:schedule-task-new' schedule.pk %}">
                <span class="glyphicon glyphicon-send"></span> Neue Aufgabe erstellen
            </a>
        </div>
    </div>

    <div class="alert alert-info" role="alert">
        Putzplan <strong>{{ schedule }}</strong> wiederholt sich am
        Wochentag: <strong>{{ schedule.weekday_as_name }}</strong>.
    </div>

    {% for tasktemplate in schedule.tasktemplate_set.all %}
        {% if tasktemplate.task_disabled %}
            <div class="panel panel-default">
        {% else %}
            <div class="panel panel-primary">
        {% endif %}
            <!-- Default panel contents -->
            <div class="panel-heading">
                <a class="btn btn-default btn-sm" role="button" href="{% url 'webinterface:task-edit' tasktemplate.pk %}">
                        <span class="glyphicon glyphicon-cog"></span>
                </a>
                {{ tasktemplate.name }} {% if tasktemplate.task_disabled %}
                <span class="label label-warning">Deaktiviert</span>{% endif %}
            </div>
            <div class="panel-body">
                <i>Hilfetext: </i>{{ tasktemplate.help_text }}
            </div>

            <!-- List group -->
            <div class="panel-footer">
                Muss zwischen <b>{{ tasktemplate.start_day_to_weekday }}</b> und
                    <b>{{ tasktemplate.end_day_to_weekday }}</b> erledigt werden.
            </div>
        </div>
    {% empty %}
        <h3>Es sind keine Aufgaben definiert.</h3>
    {% endfor %}
{% endblock %}