cleansys/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from cleansys.settings import BASE_URL, APPLY_BASE_URL_TO_URL_PATTERNS

if APPLY_BASE_URL_TO_URL_PATTERNS:
    urlpatterns = [
        url(r'^{}'.format(BASE_URL[1:]), include('webinterface.urls')),

    ]
else:
    urlpatterns = [
        url(r'^', include('webinterface.urls')),
    ]
# urlpatterns += url(r'^admin/', admin.site.urls)

putzplan_generator/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('webinterface.urls')),
]

webinterface/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from webinterface.views import *
from webinterface.api_views import *
from webinterface.form_views import *
from webinterface.decorators import *
from django.conf.urls import include
from rest_framework import routers

from django.views.generic.base import RedirectView

router = routers.DefaultRouter()  # https://www.django-rest-framework.org/api-guide/routers/#defaultrouter
router.register(r'schedules', ScheduleViewSet)
router.register(r'schedulegroups', ScheduleGroupViewSet)
router.register(r'cleaners', CleanerViewSet)
router.register(r'affiliations', AffiliationViewSet)
router.register(r'cleaningweeks', CleaningWeekViewSet)
router.register(r'assignments', AssignmentViewSet)
router.register(r'tasktemplates', TaskTemplateViewSet)
router.register(r'task', TaskViewSet)
router.register(r'dutyswitches', DutySwitchViewSet)

app_name = 'webinterface'
urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy("webinterface:cleaner-no-page")), name='welcome'),
    path('login/', LoginView.as_view(template_name="webinterface/generic_form.html",
                                     extra_context={'title': "Login", 'add_home_button': True},
                                     authentication_form=AuthFormWithSubmit), name='login'),
    path('login-per-klick/', LoginByClickView.as_view(), name='login-by-click'),
    path('logout/', login_required(LogoutView.as_view()), name='logout'),
    path('admin/', must_be_admin(AdminView.as_view()), name='admin'),
    path('documentation/', DocumentationView.as_view(), name='docs'),
    path('admin/faq', must_be_admin(AdminFAQView.as_view()), name='admin-faq'),
    path('admin/daten', must_be_admin(AdminUpdateView.as_view()), name='admin-edit'),

    path('affiliation-edit/<int:pk>/', must_be_admin(AffiliationUpdateView.as_view()), name='affiliation-edit'),
    path('affiliation-delete/<int:pk>/', must_be_admin(AffiliationDeleteView.as_view()),
         name='affiliation-delete'),
    path('putzer/<int:pk>/zugehoerigkeiten/', login_required(AffiliationNewView.as_view()),
         name='affiliation-list'),
    path('putzer/<int:pk>/zugehoerigkeiten/p<int:cleaner_page>/', login_required(AffiliationNewView.as_view()),
         name='affiliation-list-with-cleaner-page'),

    path('putzen/<int:cleaning_week_pk>/', login_required(AssignmentTasksView.as_view()),
         name='assignment-tasks'),
    path('putzen/<int:cleaning_week_pk>/s<int:schedule_page>/', login_required(AssignmentTasksView.as_view()),
         name='assignment-tasks-back-to-schedule'),
    path('putzen/<int:cleaning_week_pk>/p<int:cleaner_page>/', login_required(AssignmentTasksView.as_view()),
         name='assignment-tasks-back-to-cleaner'),
    path('assignment-create/<int:schedule_pk>/<int:page>/', must_be_admin(AssignmentCreateView.as_view()),
         name='assignment-create-back-to-schedule'),
    path('assignment-create/<int:schedule_pk>/<int:page>/<int:initial_begin>/<int:initial_end>/',
         must_be_admin(AssignmentCreateView.as_view()),
         name='assignment-create-init'),
    path('assignment-edit/<int:pk>/<int:page>/', must_be_admin(AssignmentUpdateView.as_view()),
         name='assignment-edit'),

    path('du/seite<int:page>/', login_required(CleanerView.as_view()), name='cleaner'),
    path('du/', login_required(CleanerView.as_view()), name='cleaner-no-page'),
    path('du/dienst<int:assignment_pk>/', login_required(CleanerView.as_view()), name='cleaner-no-page-to-assignment'),
    path('du/kalender/', login_required(CleanerCalendarView.as_view()), name='cleaner-calendar'),
    path('putzer-analytics/', login_required(CleanerAnalyticsView.as_view()), name='cleaner-analytics'),
    path('putzer-analytics/p<int:cleaner_page>/', login_required(CleanerAnalyticsView.as_view()),
         name='cleaner-analytics-with-cleaner-page'),

    path('putzer/neu/', must_be_admin(CleanerNewView.as_view()), name='cleaner-new'),
    path('putzer/<int:pk>/', login_required(CleanerUpdateView.as_view()),
         name='cleaner-edit'),
    path('putzer/<int:pk>/p<int:cleaner_page>', login_required(CleanerUpdateView.as_view()),
         name='cleaner-edit-with-cleaner-page'),
    path('cleaner-delete/<int:pk>/', must_be_admin(CleanerDeleteView.as_view()), name='cleaner-delete'),

    path('cleaning-week-tasks/<int:pk>/<int:page>/', must_be_admin(TaskCreateView.as_view()),
         name='cleaning-week-tasks'),
    path('cleaning-week-edit/<int:pk>/<int:page>/', must_be_admin(CleaningWeekUpdateView.as_view()),
         name='cleaning-week-edit'),
    path('cleaning-week-delete/<int:pk>/<int:page>/', must_be_admin(CleaningWeekDeleteView.as_view()),
         name='cleaning-week-delete'),

    path('tauschen/<int:assignment_pk>/<int:page>', login_required(DutySwitchNewView.as_view()),
         name='dutyswitch-create'),
    path('tausch-bearbeiten/<int:dutyswitch_pk>/<int:page>', login_required(DutySwitchUpdateView.as_view()),
         name='dutyswitch-update'),
    path('tauschanfrage-akzeptieren/<int:pk>/<int:page>', login_required(DutySwitchAcceptView.as_view()),
         name='dutyswitch-accept'),
    path('tauschanfrage-akzeptieren/<int:pk>', login_required(DutySwitchAcceptView.as_view()),
         name='dutyswitch-accept-no-cleaner-page'),
    path('tauschanfrage-loeschen/<int:pk>/<int:page>', login_required(DutySwitchDeleteView.as_view()),
         name='dutyswitch-delete'),
    path('tauschvorschlag-ablehnen/<int:pk>', login_required(DutySwitchRejectProposalView.as_view()),
         name='dutyswitch-reject-proposal'),

    path('putzplan-liste/', login_required(ScheduleList.as_view()), name='schedule-list'),
    path('putzplan/<slug:slug>/ab<int:week>/druckansicht/', login_required(SchedulePrintView.as_view()),
         name='schedule-print-view'),
    # path('putzplan/<slug:slug>/seite<int:page>/<slug:highlight_slug>/', login_required(ScheduleView.as_view()),
    #      name='schedule-highlight'),
    path('putzplan/<slug:slug>/seite<int:page>/', login_required(ScheduleView.as_view()), name='schedule'),
    path('putzplan/<slug:slug>/analytics/', login_required(ScheduleAnalyticsView.as_view()),
         name='schedule-analytics-view'),
    path('putzplan/<slug:slug>/analytics/s<int:schedule_page>/', login_required(ScheduleAnalyticsView.as_view()),
         name='schedule-analytics-view-with-schedule-page'),
    path('putzplan/<slug:slug>/', login_required(ScheduleView.as_view()), name='schedule-no-page'),

    path('schedule-new/', must_be_admin(ScheduleNewView.as_view()), name='schedule-new'),
    path('schedule-edit/<int:pk>/', must_be_admin(ScheduleUpdateView.as_view()),
         name='schedule-edit'),
    path('schedule-delete/<int:pk>/', must_be_admin(ScheduleDeleteView.as_view()),
         name='schedule-delete'),
    path('schedule/<int:pk>/tasks/', must_be_admin(ScheduleTaskList.as_view()),
         name='schedule-task-list'),
    path('schedule/<int:pk>/tasks/new/', must_be_admin(TaskTemplateNewView.as_view()),
         name='schedule-task-new'),
    path('schedule-overview', must_be_admin(ScheduleOverView.as_view()),
         name='schedule-overview'),

    path('schedule-group-new/', must_be_admin(ScheduleGroupNewView.as_view()),
         name='schedule-group-new'),
    path('schedule-group-edit/<int:pk>/', must_be_admin(ScheduleGroupUpdateView.as_view()),
         name='schedule-group-edit'),
    path('schedule-group-delete/<int:pk>/', must_be_admin(ScheduleGroupDeleteView.as_view()),
         name='schedule-group-delete'),

    path('geputzt/<int:assignment_pk>/<int:task_pk>', login_required(TaskCleanedView.as_view()),
         name='task-cleaned'),
    path('task-edit/<int:pk>/', must_be_admin(TaskTemplateUpdateView.as_view()), name='task-edit'),
    path('task-delete/<int:pk>/', must_be_admin(TaskTemplateDeleteView.as_view()), name='task-delete'),

    path('api/', include((router.urls, 'webinterface'), namespace="api"))
]

webinterface/templates/webinterface_snippets/button_to_schedule_list_page.html
<a class="btn btn-info" role="button" href="{% url 'webinterface:schedule-list' %}">
    <span class="glyphicon glyphicon-list-alt"></span> Putzpläne
</a>

webinterface/templates/webinterface_snippets/button_to_schedule_page.html
<a class="btn btn-info" role="button"
   style="white-space: normal"
        {% if back_to_schedule_page and back_to_schedule_page > 0 %}
            href="{% url 'webinterface:schedule' schedule.slug back_to_schedule_page %}"
        {% else %}
            href="{% url 'webinterface:schedule-no-page' schedule.slug %}"
        {% endif %}>
    <span class="glyphicon glyphicon-list-alt"></span> {{ schedule.name }}
</a>

webinterface/templates/webinterface_snippets/cleaner_pagination_buttons.html
<div class="row" style="padding: 1em">
    <div class="col-xs-6" style="padding: 5px">
        {% if page_obj.has_previous %}
            <a class="btn btn-default btn-block btn-sm" role="button"
               href="{% url 'webinterface:cleaner' page_obj.previous_page_number %}">
                <span class="glyphicon glyphicon-arrow-left"></span> Vorherige Seite
            </a>
        {% endif %}
    </div>
    <div class="col-xs-6" style="padding: 5px">
        {% if page_obj.has_next %}
            <a class="btn btn-default btn-block btn-sm" role="button"
               href="{% url 'webinterface:cleaner' page_obj.next_page_number %}">
                <span class="glyphicon glyphicon-arrow-right"></span> Nächste Seite
            </a>
        {% endif %}
    </div>
</div>

webinterface/templates/webinterface_snippets/cleaner_panel.html
{% with last_affiliation=cleaner.affiliation_set.last current_affiliation=cleaner.current_affiliation homeless_soon=cleaner.is_homeless_soon %}
    <div class="col-xs-12 col-sm-6" style="padding: 5px">
        <div class="panel
            {% if current_affiliation %}
                panel-info
            {% elif not last_affiliation %}
                panel-danger
            {% else %}
                panel-default
            {% endif %}">
            <div class="panel-heading">

                <h3 class="panel-title">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle pull-right"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="glyphicon glyphicon-cog"></span> <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'webinterface:cleaner-edit' cleaner.pk %}">
                                <span class="glyphicon glyphicon-cog"></span> Putzerdaten</a></li>
                            <li role="separator" class="divider"></li>
                            <li {% if not last_affiliation or homeless_soon %}class="bg-danger" {% endif %}>
                                <a href="{% url 'webinterface:affiliation-list' cleaner.pk %}">
                                    <span class="glyphicon glyphicon-home"></span> Zugehörigkeiten</a>
                            </li>
                        </ul>
                    </div>

                    <span class="glyphicon glyphicon-user"></span> {{ cleaner.name }}
                </h3>
            </div>
            <div class="panel-footer">
                {% if last_affiliation %}
                    {% if current_affiliation %}
                        In <strong>{{ current_affiliation.group }}</strong><br>
                        bis <span class="glyphicon glyphicon-calendar"></span>
                        <strong>{{ current_affiliation.end_as_date|date:"d. M. Y" }}</strong>
                    {% else %}
                        War in <strong>{{ last_affiliation.group }}</strong><br>
                        bis <span class="glyphicon glyphicon-calendar"></span>
                        <strong>{{ last_affiliation.end_as_date|date:"d. M. Y" }}</strong>
                    {% endif %}
                {% endif %}
                {% if not last_affiliation or homeless_soon %}
                    <ul style="padding: 0">
                        {% if not last_affiliation %}
                            <li class="bg-warning">
                                Dieser Putzer hat keine Zugehörigkeiten!
                                <span style="white-space: nowrap">
                                    (<span class="glyphicon glyphicon-cog"></span><span class="caret"></span>
                                    <span class="glyphicon glyphicon-menu-right"></span>
                                    <span class="glyphicon glyphicon-home"></span> Zugehörigkeiten)
                                </span>
                            </li>
                        {% endif %}
                        {% if homeless_soon %}
                            <li class="bg-warning">
                                Dieser Putzer zieht bald aus!
                                <span style="white-space: nowrap">
                                    (<span class="glyphicon glyphicon-cog"></span><span class="caret"></span>
                                    <span class="glyphicon glyphicon-menu-right"></span>
                                    <span class="glyphicon glyphicon-home"></span> Zugehörigkeiten)
                                </span>
                            </li>
                        {% endif %}
                    </ul>
                {% endif %}
            </div>
        </div>
    </div>
{% endwith %}

webinterface/templates/webinterface_snippets/home_button.html
<a class="btn btn-default" role="button"
        {% if user.is_superuser %}

            href="{% url 'webinterface:admin' %}"

        {% else %}
            {% if back_to_cleaner_page and back_to_cleaner_page > 0 %}

                href="{% url 'webinterface:cleaner' back_to_cleaner_page %}"

            {% else %}

                href="{% url 'webinterface:cleaner-no-page' %}"

            {% endif %}
        {% endif %}>
    <span class="glyphicon glyphicon-home"></span> Home
</a>

webinterface/templates/webinterface_snippets/schedule_dropdown_button.html
 <div class="col-xs-12 col-sm-6 col-lg-4" style="padding: 5px">
     <button type="button" class="btn {% if schedule.disabled %}btn-default{% else %}btn-primary{% endif %} btn-block dropdown-toggle"
             data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         <span class="glyphicon glyphicon-list-alt"></span> {{ schedule.name }} <span class="pull-right caret"></span>
         <span class="sr-only">Toggle Dropdown</span>
     </button>
     <ul class="dropdown-menu">
         <li><a href="{% url 'webinterface:schedule-no-page' schedule.slug %}">
             <span class="glyphicon glyphicon-eye-open"></span> Putzdienste</a></li>
         <li role="separator" class="divider"></li>
         <li><a href="{% url 'webinterface:schedule-edit' schedule.pk %}">
             <span class="glyphicon glyphicon-cog"></span> Bearbeiten</a></li>
         <li><a href="{% url 'webinterface:schedule-task-list' schedule.pk %}">
             <span class="glyphicon glyphicon-tags"></span> Aufgaben</a></li>
     </ul>
 </div>

webinterface/templates/webinterface_snippets/schedule_pagination_buttons.html
<div class="row">
    <div class="col-xs-6" style="padding: 5px">
        {% if page_obj.has_previous %}
            <a class="btn btn-default btn-block btn-sm" role="button"
                href="{% url 'webinterface:schedule' schedule.slug page_obj.previous_page_number %}">
                        <span class="glyphicon glyphicon-arrow-left"></span> Vorherige Seite
            </a>
        {% endif %}
    </div>
    <div class="col-xs-6" style="padding: 5px">
        {% if page_obj.has_next %}
            <a class="btn btn-default btn-block btn-sm" role="button"
               href="{% url 'webinterface:schedule' schedule.slug page_obj.next_page_number %}">
                        <span class="glyphicon glyphicon-arrow-right"></span> Nächste Seite
            </a>
        {% endif %}
    </div>
</div>

webinterface/templates/webinterface_snippets/schedule_panel.html
{% with templates_exist=schedule.tasktemplate_set.exists assignments_exist=schedule.assignment_set.exists %}
{% with groups_exist=schedule.schedulegroup_set.exists some_assignments_invalid=schedule.cleaningweek_set.assignments_invalid.exists %}
{% with assignments_running_out=schedule.assignments_are_running_out %}
<div class="col-xs-12 col-sm-6" style="padding: 5px">
    <div class="panel
            {% if schedule.disabled %}
                panel-default
            {% elif not templates_exist or not assignments_exist or not groups_exist or some_assignments_invalid or assignments_running_out %}
                panel-danger
            {% else %}
                panel-info
            {% endif %}">
        <div class="panel-heading">
            <h3 class="panel-title">
                <div class="btn-group">
                    <button type="button" class="btn btn-default dropdown-toggle pull-right"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="glyphicon glyphicon-cog"></span> <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li {% if not schedule.disabled %}{% if not assignments_exist or some_assignments_invalid or assignments_running_out %}
                                class="bg-danger"{% endif %}{% endif %}>

                            <a href="{% url 'webinterface:schedule-no-page' schedule.slug %}">
                            <span class="glyphicon glyphicon-eye-open"></span> Putzdienste</a>

                        </li>

                        <li role="separator" class="divider"></li>

                        <li {% if not schedule.disabled and not groups_exist %}
                                class="bg-danger"{% endif %}>

                            <a href="{% url 'webinterface:schedule-edit' schedule.pk %}">
                            <span class="glyphicon glyphicon-cog"></span> Bearbeiten</a>

                        </li>
                        <li {% if not schedule.disabled and not templates_exist %}
                                class="bg-danger"{% endif %}>
                            <a href="{% url 'webinterface:schedule-task-list' schedule.pk %}">
                            <span class="glyphicon glyphicon-tags"></span> Aufgaben</a>

                        </li>
                    </ul>
                </div>

                <span class="glyphicon glyphicon-list-alt"></span> {{ schedule.name }}
            </h3>
        </div>
        <div class="panel-footer">
            {% if not schedule.disabled %}
                {% if not templates_exist or not assignments_exist or not groups_exist or some_assignments_invalid or assignments_running_out %}
                    {% if not templates_exist %}
                        <ul style="padding: 0">
                            <li class="bg-warning">
                                Bitte füge Aufgaben hinzu!
                                <span style="white-space: nowrap">
                                (<span class="glyphicon glyphicon-cog"></span><span class="caret"></span>
                                <span class="glyphicon glyphicon-menu-right"></span>
                                <span class="glyphicon glyphicon-tags"></span> Aufgaben)
                            </span>
                            </li>
                        </ul>
                    {% endif %}
                    {% if not groups_exist %}
                        <ul style="padding: 0">
                            <li class="bg-warning">
                                Dieser Putzplan gehört keiner Gruppe an!
                                <span style="white-space: nowrap">
                                (<span class="glyphicon glyphicon-cog"></span><span class="caret"></span>
                                <span class="glyphicon glyphicon-menu-right"></span>
                                <span class="glyphicon glyphicon-cog"></span> Bearbeiten)
                            </span>
                            </li>
                        </ul>
                    {% endif %}
                    {% if not assignments_exist %}
                        <ul style="padding: 0">
                            <li class="bg-warning">
                                Dieser Putzplan hat noch keine Putzdienste!
                                <span style="white-space: nowrap">
                                (<span class="glyphicon glyphicon-cog"></span><span class="caret"></span>
                                <span class="glyphicon glyphicon-menu-right"></span>
                                <span class="glyphicon glyphicon-eye-open"></span> Putzdienste)
                            </span>
                            </li>
                        </ul>
                    {% endif %}
                    {% if some_assignments_invalid %}
                        <ul style="padding: 0">
                            <li class="bg-warning">
                                Bei manchen Putzwochen müssen die Putzdienste aktualisiert werden!
                                <span style="white-space: nowrap">
                                (<span class="glyphicon glyphicon-cog"></span><span class="caret"></span>
                                <span class="glyphicon glyphicon-menu-right"></span>
                                <span class="glyphicon glyphicon-eye-open"></span> Putzdienste)
                            </span>
                            </li>
                        </ul>
                    {% endif %}
                    {% if assignments_running_out %}
                        <ul style="padding: 0">
                            <li class="bg-warning">
                                Der letzte Putzdienst ist schon am
                                <strong>{{ schedule.assignment_set.last.assignment_date }}</strong>.
                                Es müssen neue Putzdienste erstellt werden!
                                <span style="white-space: nowrap">
                                (<span class="glyphicon glyphicon-cog"></span><span class="caret"></span>
                                <span class="glyphicon glyphicon-menu-right"></span>
                                <span class="glyphicon glyphicon-eye-open"></span> Putzdienste)
                            </span>
                            </li>
                        </ul>
                    {% endif %}
                {% endif %}
            {% endif %}
            <p>
                Besitzt <span class="glyphicon glyphicon-send"></span>
                <strong>{{ schedule.tasktemplate_set.count }}</strong> Aufgaben.
            </p>
            <p>
                <span class="glyphicon glyphicon-repeat"></span>
                <strong>
                    {% if schedule.frequency == 1 %}
                        jede Woche
                    {% elif schedule.frequency == 2 %}
                        in geraden Wochen
                    {% elif schedule.frequency == 3 %}
                        in ungeraden Wochen
                    {% endif %}
                </strong>
                am <span class="glyphicon glyphicon-calendar"></span>
                <strong>{{ schedule.weekday_as_name }}</strong> mit
                <span class=" glyphicon glyphicon-user "></span> <strong>{{ schedule.cleaners_per_date }}</strong>
                Putzenden pro Dienst.
            </p>
            <p>
                <span class=" glyphicon glyphicon-user "></span>
                <strong>{{ schedule.currently_active_affiliations.count }}</strong> Putzende haben derzeit eine
                Zugehörigkeit mit diesem Putzplan.
            </p>
        </div>
    </div>
</div>
{% endwith %}{% endwith %}{% endwith %}

webinterface/templates/webinterface_snippets/task_panel.html
{% if as_nav %}
    <a href="#task_{{ task.pk }}" class="btn  btn-xs btn-block
    {% if task.my_time_has_come and not task.cleaned_by %}btn-success{% else %}btn-default{% endif %}"
    style="text-align: left; white-space: nowrap; overflow: hidden">
        {% if task.cleaned_by %}
            <span class="glyphicon glyphicon-user"></span> <strong>{{ task.cleaned_by }}</strong>:
        {% endif %}
        {{ task }}
        <br>
        <span class="glyphicon glyphicon-calendar"></span>
        <strong>{{ task.start_date|date:"d.m." }} - {{ task.end_date|date:"d.m." }}</strong>
    </a>
{% else %}
    <div class="panel {% if task.my_time_has_come and not task.cleaned_by %}panel-success{% else %}panel-default{% endif %}"
         id="task_{{ task.pk }}">
        <div class="panel-heading">
            <p>
                {% if task.cleaned_by %}
                    <span class="glyphicon glyphicon-ok"></span>
                {% else %}
                    <span class="glyphicon glyphicon-play"></span>
                {% endif %}
                <strong>{{ task }}</strong>
            </p>
            {% if assignment %}
                {% if cleaner in cleaning_week.assigned_cleaners and task.my_time_has_come or user.is_superuser %}
                    {% if not user.is_superuser and task.my_time_has_come and not task.cleaned_by %}
                        <form method="POST" id="{{ assignment.pk }}__{{ task.pk }}"
                              action="{% url 'webinterface:task-cleaned' assignment.pk task.pk %}">
                            {% csrf_token %}
                            <input type="hidden" name="save" value="">
                            <input type="hidden" name="cleaned_by" value="{{ cleaner.pk }}">
                        </form>
                        <button type="submit" class="btn {% if task.my_time_has_come and not task.cleaned_by %}btn-success{% else %}btn-default{% endif %}"

                                form="{{ assignment.pk }}__{{ task.pk }}">
                            <span class="glyphicon glyphicon-saved"></span> Abhaken
                        </button>
                    {% endif %}
                    <a class="btn {% if task.my_time_has_come and not task.cleaned_by %}btn-success{% else %}btn-default{% endif %}"
                       href="{% url 'webinterface:task-cleaned' assignment.pk task.pk %}"
                       role="button">
                        <span class="glyphicon glyphicon-cog"></span>
                        {% if not task.cleaned_by %}
                            Mehr Optionen
                        {% else %}
                            Bearbeiten
                        {% endif %}
                    </a>
                {% endif %}
            {% endif %}
        </div>
        <div class="panel-body">
            <p>Bearbeitbar von <b>{{ task.start_date|date:"l, d. M Y" }}</b> bis
                <strong>{{ task.end_date|date:"l, d. M Y" }}</strong>.</p>
            {% if task.cleaned_by %}
                <p>Hat <span class="glyphicon glyphicon-user"></span> <strong>{{ task.cleaned_by }}</strong> erledigt.</p>
            {% endif %}
            <button class="btn btn-xs {% if task.my_time_has_come %}btn-info{% else %}btn-default{% endif %}"
                    data-toggle="collapse" data-target="#{{ task.pk }}_help">
                <span class="glyphicon glyphicon-info-sign"></span> Hilfetext <span class="caret"></span>
            </button>
            <div id="{{ task.pk }}_help" class="collapse">
                <p class="bg-info" style="padding: 5px">{{ task.template.help_text }}</p>
            </div>
        </div>
    </div>
{% endif %}